remote_theme: jekyll/minima 
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Pat Bergan
description: Poetry, prose, and other writing
show_downloads: false